package:
  name: twilightprincess-nightly-src
  version: {{ environ.get('MYPKG_VERSION', '') }}

source:
  fn: TwilightPrincess_src.zip
  url: ../../dist/TwilightPrincess.zip

build:
  number: {{ environ.get('MYPKG_BUILD', '') }}
  binary_relocation: False
  detect_binary_files_with_prefix: False
  noarch: generic
  include_recipe: False
  
requirements:
  run:
    - bson

about:
  home: http://modloader64.com
  license: GPL-3
  summary: Twilight Princess Library for ML64